// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class SearchEmpSortTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void searchEmpSort() {
    driver.get("https://spb.hh.ru/employer");
    driver.manage().window().setSize(new Dimension(801, 691));
    driver.findElement(By.xpath("//input[@name=\'text\']")).click();
    driver.findElement(By.xpath("//input[@name=\'text\']")).sendKeys("программист");
    driver.findElement(By.xpath("//input[@name=\'text\']")).sendKeys(Keys.ENTER);
    js.executeScript("window.scrollTo(0,347)");
    driver.findElement(By.xpath("//select[@name=\'order_by\']")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".bloko-select:nth-child(1)"));
      dropdown.findElement(By.xpath("//option[. = 'по убыванию зарплат']")).click();
    }
    driver.findElement(By.xpath("//option[@value=\'salary_desc\']")).click();
    js.executeScript("window.scrollTo(0,18)");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//a[contains(@href, \'/resume/9201c73b0000a5307e0039ed1f736563726574?query=%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%81%D1%82&source=search\')]")).click();
    vars.put("win7992", waitForWindow(2000));
    driver.switchTo().window(vars.get("win7992").toString());
  }
}
