// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class SearchSimpleQueryTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void searchSimpleQuery() {
    driver.get("https://spb.hh.ru/");
    driver.findElement(By.xpath("//input[@data-qa=\'search-input\']")).click();
    driver.findElement(By.xpath("//input[@data-qa=\'search-input\']")).sendKeys("android");
    driver.findElement(By.xpath("//button[@data-qa=\'search-button\']")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//div[contains(@data-qa,\'vacancy-serp__vacancy\')][1]//a[@data-qa=\'vacancy-serp__vacancy-title\']")).click();
    vars.put("win4315", waitForWindow(2000));
    {
      List<WebElement> elements = driver.findElements(By.xpath("//*[@data-qa=\'vacancy-response-link-top\']"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//*[@data-qa=\'vacancy-company\']"));
      assert(elements.size() > 0);
    }
  }
}
