// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class SearchEmpPaginatingTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void searchEmpPaginating() {
    driver.get("https://spb.hh.ru/employer");
    driver.manage().window().setSize(new Dimension(1253, 691));
    driver.findElement(By.xpath("//input[@name=\'text\']")).click();
    driver.findElement(By.xpath("//input[@name=\'text\']")).sendKeys("программист");
    driver.findElement(By.xpath("//input[@name=\'text\']")).sendKeys(Keys.ENTER);
    js.executeScript("window.scrollTo(0,327)");
    driver.findElement(By.xpath("//a[contains(@href, \'/search/resume?L_is_autosearch=false&area=2&clusters=true&exp_company_size=any&exp_industry=any&exp_period=last_year&logic=normal&no_magic=false&order_by=relevance&pos=position%2Cworkplace_position&text=%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%81%D1%82&page=1\')]")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//a[contains(@href, \'/resume/a2f9bc980001893ac00039ed1f4f4d6547486d?query=%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%81%D1%82&source=search\')]")).click();
    vars.put("win9180", waitForWindow(2000));
    driver.switchTo().window(vars.get("win9180").toString());
  }
}
