// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchCompanyTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchCompany() {
    driver.get("https://spb.hh.ru/");
    driver.findElement(By.xpath("//input[@data-qa=\'search-input\']")).click();
    driver.findElement(By.xpath("//input[@data-qa=\'search-input\']")).sendKeys("jetbrains");
    driver.findElement(By.xpath("//button[@data-qa=\'search-button\']")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[contains(@data-qa,\'vacancy-serp__vacancy\')]"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.xpath("//a/div[2]")).getText(), is("JetBrains"));
    driver.findElement(By.xpath("//a/div[2]")).click();
    assertThat(driver.findElement(By.xpath("//a[@data-qa=\'vacancy-serp__vacancy-employer\']")).getText(), is("JetBrains"));
  }
}
