// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchEmpExtendedTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchEmpExtended() {
    driver.get("https://spb.hh.ru/employer");
    driver.manage().window().setSize(new Dimension(1253, 691));
    driver.findElement(By.xpath("//input[@name=\'text\']")).click();
    driver.findElement(By.xpath("//input[@name=\'text\']")).sendKeys("программист");
    driver.findElement(By.xpath("//input[@name=\'text\']")).sendKeys(Keys.ENTER);
    driver.findElement(By.xpath("//span[contains(.,\'Расширенный поиск\')]")).click();
    driver.findElement(By.xpath("(//input[@value=\'\'])[6]")).click();
    driver.findElement(By.xpath("(//input[@value=\'\'])[6]")).sendKeys("80000");
    driver.findElement(By.xpath("//input[@data-qa=\'resumes-search-wizard-item-keyword\']")).click();
    driver.findElement(By.xpath("//input[@data-qa=\'resumes-search-wizard-item-keyword\']")).sendKeys("программист");
    driver.findElement(By.xpath("//input[@data-qa=\'resumes-search-wizard-item-keyword\']")).sendKeys(Keys.ENTER);
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[@data-qa=\'resume-serp__results-search\']")));
    }
  }
}
